### ISSUE TITLE
The shortcut keys for the automatic scrambling is missing

### ISSUE THREAD

**Issue by Astrochicken1** [drioemgaoin/WPFRubbikCubeSolver#9]
It would be helpful to specify it in the read me.

**Comment by drioemgaoin** [comment]
Are you sure? Normally you need to click on the key 'M' as mentioned in the readme. Just check it and keep me in touch

**Comment by Astrochicken1** [comment]
To keep the shortcuts mnemonic would you agree to follow the move [letters from this reference](http://ruwix.com/the-rubiks-cube/notation/advanced/)?

I was thinking counter clockwise moves could then be done by holding with shift combinations. Or else it is really not mnemonic.
